<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="8.0.0" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="StackExchange.Redis" Version="2.7.33" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MeetingSystem.Common\MeetingSystem.Common.csproj" />
    <ProjectReference Include="..\MeetingSystem.DBFactory\MeetingSystem.DBFactory.csproj" />
    <ProjectReference Include="..\MeetingSystem.IService\MeetingSystem.IService.csproj" />
    <ProjectReference Include="..\MeetingSystem.Model\MeetingSystem.Model.csproj" />
    <ProjectReference Include="..\MeetingSystem.Service\MeetingSystem.Service.csproj" />
  </ItemGroup>

</Project>
